Repository SKHUED-IN/skhuedin, pull requests merged in 2021-06, with the labels that each got.

#133 [FEAT] readme update
  README.md
Labels: 개발

#132 [FEAT] 외장 DB 설정을 위한 추가
  build.gradle
  src/main/resources/application-local.yml
Labels: 개발

#136 [FEAT] test 전용 application.yml 수정
  src/main/java/com/skhuedin/skhuedin/controller/AdminController.java
  src/main/java/com/skhuedin/skhuedin/domain/Posts.java
  src/test/java/com/skhuedin/skhuedin/service/BlogServiceTest.java
  src/test/resources/application.yml
Labels: 개발

#140 [FEAT] admin 게시글 관리 조회 및 검색 기능 구현
  src/main/java/com/skhuedin/skhuedin/controller/admin/AdminMainController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminApiController.java
  src/main/java/com/skhuedin/skhuedin/dto/posts/PostsAdminMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/repository/PostsRepository.java
  src/main/java/com/skhuedin/skhuedin/service/PostsService.java
  src/main/resources/data.sql
  src/main/resources/static/css/admin/common.css
  src/main/resources/static/css/admin/posts.css
  src/main/resources/static/css/reset.css
  src/main/resources/templates/admin/admin-main.html
  src/main/resources/templates/admin/admin-posts.html
  src/main/resources/templates/admin/example.html
  src/main/resources/templates/fragments/admin-body-footer.html
  src/main/resources/templates/fragments/admin-body-header.html
  src/main/resources/templates/fragments/admin-header.html
Labels: 개발, 논의🙌

#141 [FEAT] 소셜 로그아웃 구현
  src/main/java/com/skhuedin/skhuedin/social/OauthController.java
  src/main/java/com/skhuedin/skhuedin/social/OauthService.java
  src/main/java/com/skhuedin/skhuedin/social/SocialOauth.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleOauth.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoOauth.java
  src/main/java/com/skhuedin/skhuedin/social/naver/NaverOauth.java
  src/main/resources/templates/contents/kakaoLogin.html
Labels: 개발

#148 [FEAT] admin kakao social login
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminApiController.java
  src/main/resources/static/css/admin/common.css
  src/main/resources/templates/admin/admin-main.html
  src/main/resources/templates/admin/admin-posts.html
  src/main/resources/templates/fragments/admin-body-header.html
  src/main/resources/templates/fragments/admin-header.html
  src/test/java/com/skhuedin/skhuedin/controller/admin/api/CategoryAdminApiControllerTest.java
Labels: 개발

#150 [FEAT] category create/delete/ update + 이름/생성일/가중치 정렬
  1
  src/main/java/com/skhuedin/skhuedin/controller/AdminController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/AdminMainController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminCategoryApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/MainApiController.java
  src/main/java/com/skhuedin/skhuedin/repository/CategoryRepository.java
  src/main/java/com/skhuedin/skhuedin/service/CategoryService.java
  src/main/resources/data.sql
  src/main/resources/templates/admin/admin-category-detail.html
  src/main/resources/templates/admin/admin-category.html
  src/main/resources/templates/admin/admin-create-category.html
  src/test/java/com/skhuedin/skhuedin/controller/admin/api/AdminUserApiControllerTest.java
Labels: 개발

#151 [FEAT] admin comment와 question 검색 및 조회 기능 구현
  src/main/java/com/skhuedin/skhuedin/common/exception/CommonExceptionAdvice.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/AdminMainController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminUserApiController.java
  src/main/java/com/skhuedin/skhuedin/dto/posts/PostsAdminMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/question/QuestionAdminMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/repository/QuestionRepository.java
  src/main/java/com/skhuedin/skhuedin/service/QuestionService.java
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/admin/posts-detail.html
  src/main/resources/templates/admin/posts.html
  src/main/resources/templates/admin/question-detail.html
  src/main/resources/templates/admin/question.html
  src/main/resources/templates/fragments/admin-body-header.html
  src/test/java/com/skhuedin/skhuedin/controller/admin/AdminMainControllerTest.java
  src/test/java/com/skhuedin/skhuedin/controller/admin/api/AdminUserApiControllerTest.java
Labels: 개발

#156 [FEAT] comment 간소화
  src/main/java/com/skhuedin/skhuedin/domain/Comment.java
  src/main/java/com/skhuedin/skhuedin/dto/blog/BlogMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/comment/CommentMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/comment/CommentSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/repository/BlogRepository.java
  src/main/java/com/skhuedin/skhuedin/repository/CommentRepository.java
  src/main/java/com/skhuedin/skhuedin/repository/UserRepository.java
  src/main/java/com/skhuedin/skhuedin/service/CommentService.java
  src/main/java/com/skhuedin/skhuedin/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/data.sql
  src/main/resources/templates/admin/question-detail.html
  src/test/java/com/skhuedin/skhuedin/dto/comment/CommentSaveRequestDtoTest.java
  src/test/java/com/skhuedin/skhuedin/repository/CommentRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/service/CommentServiceTest.java
Labels: 개발

#159 [FIX] fragments 경로로 인한 버그 수정
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminCategoryApiController.java
  src/main/resources/templates/admin/category-detail.html
  src/main/resources/templates/admin/create-category.html
  src/main/resources/templates/admin/example.html
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/admin/posts-detail.html
  src/main/resources/templates/admin/question-detail.html
  src/main/resources/templates/admin/question.html
  src/main/resources/templates/admin/suggestions.html
  src/main/resources/templates/admin/users-detail.html
Labels: 개발, 우선순위:상❕

#157 [FEAT] 블로그 조회 로직 생성
  src/main/java/com/skhuedin/skhuedin/controller/admin/AdminMainController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminBlogsApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminUserApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/PostsApiController.java
  src/main/java/com/skhuedin/skhuedin/service/BlogService.java
  src/main/resources/templates/admin/blogs.html
Labels: 개발

#163 [FEAT] user id로 blog를 조회하는 로직 추가
  src/main/java/com/skhuedin/skhuedin/controller/api/UserApiController.java
  src/main/java/com/skhuedin/skhuedin/dto/blog/BlogMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/repository/BlogRepository.java
  src/main/java/com/skhuedin/skhuedin/service/BlogService.java
  src/main/java/com/skhuedin/skhuedin/service/PostsService.java
  src/main/java/com/skhuedin/skhuedin/service/UserService.java
Labels: 개발

#161 [FEAT] 소셜 설정 파일 분리
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleOauth.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoOauth.java
  src/main/java/com/skhuedin/skhuedin/social/naver/NaverOauth.java
Labels: 개발

#165 [FIX] test 관련 application.yml 수정
  src/test/resources/application.yml
Labels: 논의🙌, 우선순위:상❕

#167 [FEAT] OuathController dto 수정
  src/main/java/com/skhuedin/skhuedin/controller/response/CheckTokenWithCommonResponse.java
  src/main/java/com/skhuedin/skhuedin/domain/Blog.java
  src/main/java/com/skhuedin/skhuedin/domain/User.java
  src/main/java/com/skhuedin/skhuedin/dto/blog/BlogMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/token/AccessTokenRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/token/TokenMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/service/BlogService.java
  src/main/java/com/skhuedin/skhuedin/service/UserService.java
  src/main/java/com/skhuedin/skhuedin/social/OauthController.java
  src/main/resources/data.sql
  src/test/java/com/skhuedin/skhuedin/repository/BlogRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/repository/UserRepositoryTest.java
Labels: 개발

#168 [TEST] AdminControllerApi 분리 / category Test 전체 로직 점검
  build.gradle
  src/main/java/com/skhuedin/skhuedin/controller/admin/AdminMainController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminCategoryApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminPostsApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminQuestionsApiController.java
  src/main/java/com/skhuedin/skhuedin/service/CategoryService.java
  src/test/java/com/skhuedin/skhuedin/controller/admin/AdminMainControllerTest.java
  src/test/java/com/skhuedin/skhuedin/controller/admin/api/AdminUserApiControllerTest.java
  src/test/java/com/skhuedin/skhuedin/controller/admin/api/CategoryAdminApiControllerTest.java
  src/test/java/com/skhuedin/skhuedin/service/CategoryServiceTest.java
Labels: 테스트

#171 [FEAT] 책장 최초 저장 시 posts 부분 size별 처리 및 posts 로직 정리
  build.gradle
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminCategoryApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminPostsApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminQuestionsApiController.java
  src/main/java/com/skhuedin/skhuedin/domain/User.java
  src/main/java/com/skhuedin/skhuedin/dto/category/CategoryMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/posts/PostsAdminResponseDto.java
  src/main/java/com/skhuedin/skhuedin/repository/CategoryRepository.java
  src/main/java/com/skhuedin/skhuedin/repository/PostsRepository.java
  src/main/java/com/skhuedin/skhuedin/service/CategoryService.java
  src/main/java/com/skhuedin/skhuedin/service/PostsService.java
  src/main/java/com/skhuedin/skhuedin/service/UserService.java
  src/main/resources/data.sql
  src/test/java/com/skhuedin/skhuedin/repository/PostsRepositoryTest.java
Labels: 개발

#174 [FEAT] blog 관련 기능 정리 및 테스트 코드 확인
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminBlogsApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/BlogApiController.java
  src/main/java/com/skhuedin/skhuedin/dto/blog/BlogAdminMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/repository/BlogRepository.java
  src/main/java/com/skhuedin/skhuedin/service/BlogService.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleInnerProfile.java
  src/main/resources/templates/admin/blogs.html
  src/test/java/com/skhuedin/skhuedin/service/BlogServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/PostsServiceTest.java
Labels: 개발, 테스트

#175 [FEAT] user admin dto 분리 및 user admin 기능 정리
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminUserApiController.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserAdminMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/repository/UserRepository.java
  src/main/java/com/skhuedin/skhuedin/service/UserService.java
  src/test/java/com/skhuedin/skhuedin/service/UserServiceTest.java
Labels: 개발, 테스트

#178 [FEAT] main controller 추가 및 swagger 접근 버튼 추가
  src/main/java/com/skhuedin/skhuedin/controller/MainController.java
  src/main/resources/static/css/admin/common.css
  src/main/resources/static/css/admin/posts.css
  src/main/resources/static/images/swagger.png
  src/main/resources/templates/admin/main.html
Labels: 개발

#181 [FEAT] 긴 길이의 문자열 저장을 위한 content 필드 수정
  src/main/java/com/skhuedin/skhuedin/domain/Posts.java
  src/main/java/com/skhuedin/skhuedin/dto/posts/PostsSaveRequestDto.java
  src/test/java/com/skhuedin/skhuedin/dto/posts/PostsSaveRequestDtoTest.java
  src/test/java/com/skhuedin/skhuedin/repository/PostsRepositoryTest.java
Labels: 개발

#182 [FEAT] question 및 comment 기능 정리
  src/main/java/com/skhuedin/skhuedin/controller/api/CommentApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/PostsApiController.java
  src/main/java/com/skhuedin/skhuedin/repository/CommentRepository.java
  src/main/java/com/skhuedin/skhuedin/service/CommentService.java
  src/main/java/com/skhuedin/skhuedin/service/QuestionService.java
Labels: 개발

#184 [FEAT] 권한 관련 기능 수정 및 보완
  src/main/java/com/skhuedin/skhuedin/controller/admin/AdminMainController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminBlogsApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminCategoryApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminPostsApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminQuestionsApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminUserApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/BlogApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/PostsApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/UserApiController.java
  src/main/resources/templates/admin/blogs.html
  src/main/resources/templates/admin/category-detail.html
  src/main/resources/templates/admin/category.html
  src/main/resources/templates/admin/create-category.html
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/admin/posts-detail.html
  src/main/resources/templates/admin/posts.html
  src/main/resources/templates/admin/question-detail.html
  src/main/resources/templates/admin/question.html
  src/main/resources/templates/admin/suggestions.html
  src/main/resources/templates/admin/users.html
  src/main/resources/templates/fragments/admin-header.html
Labels: 개발

#186 [FEAT] admin page 로그인 수정 및 로그아웃 추가
  src/main/resources/static/js/kakao.js
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/admin/users.html
  src/main/resources/templates/fragments/admin-body-footer.html
  src/main/resources/templates/fragments/admin-body-header.html
Labels: 개발

#191 [FEAT] admin 로그인/로그아웃 시점 reload
  src/main/resources/static/js/kakao.js
Labels: 개발

#187 [FEAT] google save 필드 변경/ google social test/ categoryTest r권한 설정
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleOauth.java
  src/test/java/com/skhuedin/skhuedin/controller/admin/api/AdminUserApiControllerTest.java
  src/test/java/com/skhuedin/skhuedin/controller/admin/api/CategoryAdminApiControllerTest.java
  src/test/java/com/skhuedin/skhuedin/service/BlogServiceTest.java
  src/test/java/com/skhuedin/skhuedin/social/OauthControllerTest.java
  src/test/java/com/skhuedin/skhuedin/social/OauthServiceTest.java
  src/test/resources/application.yml
Labels: 테스트

#189 [REFACTOR] user 로직 전체 점검
  src/main/java/com/skhuedin/skhuedin/controller/admin/api/AdminUserApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/UserApiController.java
  src/main/java/com/skhuedin/skhuedin/infra/LoginRequest.java
  src/main/java/com/skhuedin/skhuedin/infra/Role.java
  src/main/java/com/skhuedin/skhuedin/repository/UserRepository.java
  src/main/java/com/skhuedin/skhuedin/service/UserService.java
  src/main/java/com/skhuedin/skhuedin/social/OauthController.java
  src/main/java/com/skhuedin/skhuedin/social/OauthService.java
  src/main/java/com/skhuedin/skhuedin/social/SocialOauth.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleOauth.java
  src/main/resources/templates/admin/users-detail.html
  src/test/java/com/skhuedin/skhuedin/service/UserServiceTest.java
Labels: 리팩토링

#194 [FIX] test 수정
  src/main/java/com/skhuedin/skhuedin/domain/Posts.java
  src/test/java/com/skhuedin/skhuedin/social/OauthControllerTest.java
  src/test/resources/application.yml
Labels: 우선순위:상❕, 테스트
