Repository SKHUED-IN/skhuedin, pull requests merged in 2021-04, with the labels that each got.

#15 [TEST] Talent, Roadmap, RoadmapItem, TalentCategory 테스트 코드 추가
  src/main/java/com/skhuedin/skhuedin/SkhuedInApplication.java
  src/main/java/com/skhuedin/skhuedin/domain/BaseEntity.java
  src/main/java/com/skhuedin/skhuedin/domain/Follow.java
  src/main/java/com/skhuedin/skhuedin/domain/Provider.java
  src/main/java/com/skhuedin/skhuedin/domain/Question.java
  src/main/java/com/skhuedin/skhuedin/domain/QuestionCategory.java
  src/main/java/com/skhuedin/skhuedin/domain/Roadmap.java
  src/main/java/com/skhuedin/skhuedin/domain/RoadmapItem.java
  src/main/java/com/skhuedin/skhuedin/domain/SkillCategory.java
  src/main/java/com/skhuedin/skhuedin/domain/Talent.java
  src/main/java/com/skhuedin/skhuedin/domain/User.java
  src/test/java/com/skhuedin/skhuedin/domain/RoadmapItemTest.java
  src/test/java/com/skhuedin/skhuedin/domain/RoadmapTest.java
  src/test/java/com/skhuedin/skhuedin/domain/SkillCategoryTest.java
  src/test/java/com/skhuedin/skhuedin/domain/TalentTest.java
Labels: 개발, 테스트

#22 [FEAT] kakao 소셜 로그인 구현
  build.gradle
  src/main/java/com/skhuedin/skhuedin/domain/Comment.java
  src/main/java/com/skhuedin/skhuedin/kakao/KakaoController.java
  src/main/java/com/skhuedin/skhuedin/kakao/KakaoProfile.java
  src/main/java/com/skhuedin/skhuedin/kakao/OAuthToken.java
  src/main/resources/static/html/login.html
  src/main/resources/static/img/kakao_login_medium_wide.png
Labels: 개발

#27 [FEAT] kakao profile 값 저장
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/com/skhuedin/skhuedin/repository/UserRepository.java
  src/main/java/com/skhuedin/skhuedin/service/UserService.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoController.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoProfile.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoService.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/OAuthToken.java
  src/main/resources/static/html/login.html
  src/main/resources/templates/kakaoLogin.html
  src/main/resources/templates/kakaoProfile.html
Labels: 개발

#29 [FEAT] 엔티티 기본키 생성 전략 변경
  src/main/java/com/skhuedin/skhuedin/domain/Blog.java
  src/main/java/com/skhuedin/skhuedin/domain/Category.java
  src/main/java/com/skhuedin/skhuedin/domain/Comment.java
  src/main/java/com/skhuedin/skhuedin/domain/Follow.java
  src/main/java/com/skhuedin/skhuedin/domain/Post.java
  src/main/java/com/skhuedin/skhuedin/domain/Question.java
  src/main/java/com/skhuedin/skhuedin/domain/User.java
Labels: 개발, 테스트

#38 [FEAT] question 기능 추가
  src/main/java/com/skhuedin/skhuedin/controller/ExceptionController.java
  src/main/java/com/skhuedin/skhuedin/controller/QuestionApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/response/BasicResponse.java
  src/main/java/com/skhuedin/skhuedin/controller/response/CommonResponse.java
  src/main/java/com/skhuedin/skhuedin/controller/response/ErrorResponse.java
  src/main/java/com/skhuedin/skhuedin/domain/Question.java
  src/main/java/com/skhuedin/skhuedin/dto/question/QuestionMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/question/QuestionSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/repository/QuestionRepository.java
  src/main/java/com/skhuedin/skhuedin/repository/UserRepository.java
  src/main/java/com/skhuedin/skhuedin/service/QuestionService.java
  src/main/java/com/skhuedin/skhuedin/service/UserService.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/skhuedin/skhuedin/domain/QuestionTest.java
  src/test/java/com/skhuedin/skhuedin/repository/QuestionRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/service/QuestionServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/UserServiceTest.java
Labels: 개발

#37 [FEAT] google user save
  src/main/java/com/skhuedin/skhuedin/social/OauthController.java
  src/main/java/com/skhuedin/skhuedin/social/OauthService.java
  src/main/java/com/skhuedin/skhuedin/social/SocialOauth.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleController.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleInnerProfile.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleOAuthResponse.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleOauth.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleService.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoOauth.java
  src/main/java/com/skhuedin/skhuedin/social/naver/NaverOauth.java
  src/main/resources/templates/googleLogin.html
  src/main/resources/templates/googleProfile.html
  src/main/resources/templates/kakaoLogin.html
Labels: 개발, 우선순위:상❕

#40 [FEAT] comment 기능 정리 및 구현
  src/main/java/com/skhuedin/skhuedin/controller/CommentApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/ExceptionController.java
  src/main/java/com/skhuedin/skhuedin/controller/QuestionApiController.java
  src/main/java/com/skhuedin/skhuedin/domain/Comment.java
  src/main/java/com/skhuedin/skhuedin/dto/comment/CommentMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/comment/CommentSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/question/QuestionMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/repository/CommentRepository.java
  src/main/java/com/skhuedin/skhuedin/service/CommentService.java
  src/main/java/com/skhuedin/skhuedin/service/QuestionService.java
  src/main/resources/data.sql
  src/test/java/com/skhuedin/skhuedin/repository/CommentRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/repository/QuestionRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/service/CommentServiceTest.java
Labels: 개발

#41 [FEAT] social 공통 양식으로 수정
  src/main/java/com/skhuedin/skhuedin/controller/BaseController.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoController.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoOauth.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoService.java
  src/main/resources/templates/kakaoLogin.html
Labels: 개발, 리팩토링

#42 [FEAT] naver 로그인 구현
  src/main/java/com/skhuedin/skhuedin/social/naver/NaverOauth.java
  src/main/java/com/skhuedin/skhuedin/social/naver/NaverProfile.java
  src/main/resources/templates/kakaoLogin.html
Labels: 개발

#45 [FEAT] blog 기능 정리 및 구현
  src/main/java/com/skhuedin/skhuedin/controller/BlogApiController.java
  src/main/java/com/skhuedin/skhuedin/dto/blog/BlogMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/blog/BlogSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/repository/BlogRepository.java
  src/main/java/com/skhuedin/skhuedin/service/BlogService.java
  src/main/resources/data.sql
  src/test/java/com/skhuedin/skhuedin/repository/CommentRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/repository/QuestionRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/service/BlogServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/CommentServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/QuestionServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/UserServiceTest.java
  src/test/resources/application.yml
Labels: 개발

#48 [FEAT] posts repository, service 구현
  src/main/java/com/skhuedin/skhuedin/domain/Posts.java
  src/main/java/com/skhuedin/skhuedin/dto/posts/PostsMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/posts/PostsSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/repository/PostsRepository.java
  src/main/java/com/skhuedin/skhuedin/service/PostsService.java
  src/test/java/com/skhuedin/skhuedin/domain/PostsTest.java
  src/test/java/com/skhuedin/skhuedin/repository/PostsRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/service/PostsServiceTest.java
Labels: 개발
