Repository SKHUED-IN/skhuedin, pull requests merged in 2021-05, with the labels that each got.

#57 [FEAT] h2 내장DB 설정을 위한 수정
  src/main/resources/application.yml
Labels: 개발

#65 [FEAT] code -> token 을 받아서 로그인 처리하도록 로직 변경
  src/main/java/com/skhuedin/skhuedin/dto/user/UserMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/social/OauthController.java
  src/main/java/com/skhuedin/skhuedin/social/OauthService.java
  src/main/java/com/skhuedin/skhuedin/social/SocialLoginTypeConverter.java
  src/main/java/com/skhuedin/skhuedin/social/SocialOauth.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleOauth.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoOauth.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/OAuthToken.java
  src/main/java/com/skhuedin/skhuedin/social/naver/NaverOauth.java
Labels: 개발, 논의🙌

#69 [TEST] test code 점검
  src/test/java/com/skhuedin/skhuedin/service/BlogServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/CommentServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/PostsServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/QuestionServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/UserServiceTest.java
  src/test/java/com/skhuedin/skhuedin/social/GoogleOauthTest.java
  src/test/java/com/skhuedin/skhuedin/social/KakaoOauthTest.java
  src/test/java/com/skhuedin/skhuedin/social/NaverOauthTest.java
  src/test/resources/application.yml
  src/test/resources/truncate.sql
Labels: 개발, 테스트

#71 [FEAT] posts 관련 기능 및 blog 수정
  src/main/java/com/skhuedin/skhuedin/controller/PostsApiController.java
  src/main/java/com/skhuedin/skhuedin/dto/blog/BlogMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/service/BlogService.java
  src/main/resources/data.sql
Labels: 개발

#76 [FEAT] front 요구사항 반영
  src/main/java/com/skhuedin/skhuedin/config/WebMvcConfig.java
  src/main/java/com/skhuedin/skhuedin/infra/TokenResponse.java
  src/main/java/com/skhuedin/skhuedin/social/OauthController.java
Labels: 개발, 우선순위:상❕

#78 [FEAT] follow 전반적인 수정
  src/main/java/com/skhuedin/skhuedin/controller/FollowApiController.java
  src/main/java/com/skhuedin/skhuedin/domain/Follow.java
  src/main/java/com/skhuedin/skhuedin/dto/follow/FollowMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/follow/FollowSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/repository/FollowRepository.java
  src/main/java/com/skhuedin/skhuedin/service/FollowService.java
  src/test/java/com/skhuedin/skhuedin/repository/FollowRepositoryTest.java
Labels: 개발, 리팩토링

#81 [FEAT] code -> accessToken 으로 변경
  src/main/java/com/skhuedin/skhuedin/social/OauthController.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleAuthToken.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleInnerProfile.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleOAuthResponse.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleOauth.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleProfile.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoOauth.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/OAuthToken.java
  src/main/java/com/skhuedin/skhuedin/social/naver/NaverOauth.java
Labels: 개발

#80 [FEAT] n + 1문제 확인 위한 테스트 추가 및 수정
  src/main/java/com/skhuedin/skhuedin/repository/CommentRepository.java
  src/main/java/com/skhuedin/skhuedin/repository/QuestionRepository.java
  src/main/java/com/skhuedin/skhuedin/service/QuestionService.java
  src/test/java/com/skhuedin/skhuedin/repository/CommentRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/repository/QuestionRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/service/QuestionServiceTest.java
Labels: 개발, 논의🙌

#88 [REFACTOR] swagger 수정을 위한 gradle 수정
  build.gradle
Labels: 개발, 리팩토링

#86 [FEAT] 인기순 조회를 위한 정렬 추가
  src/main/java/com/skhuedin/skhuedin/controller/BlogApiController.java
  src/main/java/com/skhuedin/skhuedin/domain/Blog.java
  src/main/java/com/skhuedin/skhuedin/domain/Posts.java
  src/main/java/com/skhuedin/skhuedin/repository/BlogRepository.java
  src/main/java/com/skhuedin/skhuedin/service/BlogService.java
  src/main/resources/data.sql
  src/test/java/com/skhuedin/skhuedin/repository/BlogRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/service/UserServiceTest.java
Labels: 개발

#94 [FEAT] blog 정렬 조건 추가
  src/main/java/com/skhuedin/skhuedin/common/exception/ExceptionController.java
  src/main/java/com/skhuedin/skhuedin/controller/BlogApiController.java
  src/main/java/com/skhuedin/skhuedin/repository/BlogRepository.java
  src/main/java/com/skhuedin/skhuedin/service/BlogService.java
  src/test/java/com/skhuedin/skhuedin/repository/BlogRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/repository/PostsRepositoryTest.java
Labels: 개발

#97 refactor: 자동정렬을 활용하여 표준에 맞춘 파일 서식 지정
  src/main/java/com/skhuedin/skhuedin/config/SwaggerConfig.java
  src/main/java/com/skhuedin/skhuedin/controller/FollowApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/QuestionApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/UserApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/response/TokenWithCommonResponse.java
  src/main/java/com/skhuedin/skhuedin/domain/Category.java
  src/main/java/com/skhuedin/skhuedin/dto/follow/FollowSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/posts/PostsSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/repository/UserRepository.java
  src/main/java/com/skhuedin/skhuedin/service/PostsService.java
  src/main/java/com/skhuedin/skhuedin/service/QuestionService.java
  src/main/java/com/skhuedin/skhuedin/social/OauthController.java
  src/main/java/com/skhuedin/skhuedin/social/OauthService.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleInnerProfile.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoOauth.java
  src/main/resources/data.sql
  src/main/resources/templates/login.js
  src/test/java/com/skhuedin/skhuedin/repository/BlogRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/service/BlogServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/CommentServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/PostsServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/QuestionServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/UserServiceTest.java
Labels: 개발, 리팩토링

#98 [FEAT] token 발급 page 및 swagger 수정
  src/main/java/com/skhuedin/skhuedin/config/SwaggerConfig.java
  src/main/java/com/skhuedin/skhuedin/controller/BlogApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/CommentApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/FollowApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/PostsApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/QuestionApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/UserApiController.java
  src/main/java/com/skhuedin/skhuedin/infra/LoginRequest.java
  src/main/java/com/skhuedin/skhuedin/interceptor/AuthorizationExtractor.java
  src/main/java/com/skhuedin/skhuedin/repository/UserRepository.java
  src/main/java/com/skhuedin/skhuedin/service/UserService.java
  src/main/java/com/skhuedin/skhuedin/social/OauthController.java
  src/main/java/com/skhuedin/skhuedin/social/OauthService.java
  src/main/java/com/skhuedin/skhuedin/social/SocialOauth.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleOauth.java
  src/main/java/com/skhuedin/skhuedin/social/naver/NaverOauth.java
  src/main/resources/data.sql
Labels: 개발

#100 [FEAT] user update 부분 수정
  src/main/java/com/skhuedin/skhuedin/config/RestTemplateConfig.java
  src/main/java/com/skhuedin/skhuedin/controller/UserApiController.java
  src/main/java/com/skhuedin/skhuedin/domain/User.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserUpdateDto.java
  src/main/java/com/skhuedin/skhuedin/service/UserService.java
  src/main/java/com/skhuedin/skhuedin/social/OauthService.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleOauth.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoOauth.java
  src/main/java/com/skhuedin/skhuedin/social/naver/NaverOauth.java
  src/test/java/com/skhuedin/skhuedin/domain/PostsTest.java
  src/test/java/com/skhuedin/skhuedin/domain/QuestionTest.java
Labels: 개발

#102 [FEAT] Spring validation 추가
  build.gradle
  src/main/java/com/skhuedin/skhuedin/common/exception/CommonExceptionAdvice.java
  src/main/java/com/skhuedin/skhuedin/common/exception/ExceptionController.java
  src/main/java/com/skhuedin/skhuedin/controller/BlogApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/CommentApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/FollowApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/PostsApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/QuestionApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/UserApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/response/ErrorResponse.java
  src/main/java/com/skhuedin/skhuedin/domain/User.java
  src/main/java/com/skhuedin/skhuedin/dto/blog/BlogSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/comment/CommentSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/follow/FollowSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/posts/PostsSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/question/QuestionSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserUpdateDto.java
  src/main/java/com/skhuedin/skhuedin/service/UserService.java
  src/main/resources/data.sql
  src/test/java/com/skhuedin/skhuedin/domain/PostsTest.java
  src/test/java/com/skhuedin/skhuedin/domain/QuestionTest.java
  src/test/java/com/skhuedin/skhuedin/dto/blog/BlogSaveRequestDtoTest.java
  src/test/java/com/skhuedin/skhuedin/dto/comment/CommentSaveRequestDtoTest.java
  src/test/java/com/skhuedin/skhuedin/dto/follow/FollowSaveRequestDtoTest.java
  src/test/java/com/skhuedin/skhuedin/dto/posts/PostsSaveRequestDtoTest.java
  src/test/java/com/skhuedin/skhuedin/dto/question/QuestionSaveRequestDtoTest.java
  src/test/java/com/skhuedin/skhuedin/dto/user/UserUpdateDtoTest.java
  src/test/java/com/skhuedin/skhuedin/repository/BlogRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/repository/CommentRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/repository/FollowRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/repository/PostsRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/repository/QuestionRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/service/BlogServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/CommentServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/PostsServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/QuestionServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/UserServiceTest.java
Labels: 개발

#104 [FEAT] 책장에 profile 설정 및 수정 기능 추가
  src/main/java/com/skhuedin/skhuedin/common/exception/CommonExceptionAdvice.java
  src/main/java/com/skhuedin/skhuedin/config/WebMvcConfig.java
  src/main/java/com/skhuedin/skhuedin/controller/BlogApiController.java
  src/main/java/com/skhuedin/skhuedin/domain/Blog.java
  src/main/java/com/skhuedin/skhuedin/domain/File.java
  src/main/java/com/skhuedin/skhuedin/domain/User.java
  src/main/java/com/skhuedin/skhuedin/dto/blog/BlogMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/blog/BlogSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/dto/file/FileMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/file/FileSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/repository/BlogRepository.java
  src/main/java/com/skhuedin/skhuedin/repository/FileRepository.java
  src/main/java/com/skhuedin/skhuedin/service/BlogService.java
  src/main/java/com/skhuedin/skhuedin/service/FileService.java
  src/main/java/com/skhuedin/skhuedin/util/MD5Generator.java
  src/main/resources/data.sql
  src/main/resources/static/profile/user.png
  src/test/java/com/skhuedin/skhuedin/domain/PostsTest.java
  src/test/java/com/skhuedin/skhuedin/dto/blog/BlogSaveRequestDtoTest.java
  src/test/java/com/skhuedin/skhuedin/repository/BlogRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/repository/PostsRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/service/BlogServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/PostsServiceTest.java
Labels: 개발

#110 [FEAT]최초 회원 가입인지 아닌지 알려주기 위한 로직
  src/main/java/com/skhuedin/skhuedin/controller/UserApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/response/CheckTokenWithCommonResponse.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/social/OauthController.java
Labels: 개발, 프론트

#111 [FEAT] 109 이슈에 대한 null 처리
  src/main/java/com/skhuedin/skhuedin/controller/UserApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/response/CheckTokenWithCommonResponse.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserUpdateDto.java
  src/main/java/com/skhuedin/skhuedin/service/UserService.java
  src/main/java/com/skhuedin/skhuedin/social/OauthController.java
Labels: 개발

#112 [FEAT] google login 수정 + response 수정
  src/main/java/com/skhuedin/skhuedin/dto/user/UserMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleInnerProfile.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleOauth.java
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleProfile.java
  src/main/java/com/skhuedin/skhuedin/social/kakao/KakaoOauth.java
Labels: 개발

#113 [FEAT] google dto 수정
  src/main/java/com/skhuedin/skhuedin/social/google/GoogleProfile.java
Labels: 프론트

#108 [FEAT] 외부에 profile 정보를 저장하기 위해 수정
  src/main/java/com/skhuedin/skhuedin/config/WebMvcConfig.java
  src/main/java/com/skhuedin/skhuedin/controller/BlogApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/response/CheckTokenWithCommonResponse.java
  src/main/java/com/skhuedin/skhuedin/util/MD5Generator.java
  src/main/resources/application.yml
Labels: 개발, 논의🙌

#119 [FEAT] 자체 token을 검증할 수 있는 api 추가
  src/main/java/com/skhuedin/skhuedin/controller/UserApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/response/CommonResponse.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserTokenValidationDto.java
  src/test/java/com/skhuedin/skhuedin/dto/user/UserUpdateDtoTest.java
  src/test/resources/application.yml
Labels: 개발

#120 [FEAT] 배포 관련 설정
  .gitignore
  .travis.yml
  appspec.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  scripts/health.sh
  scripts/profile.sh
  scripts/start.sh
  scripts/stop.sh
  scripts/switch.sh
  src/main/java/com/skhuedin/skhuedin/config/WebMvcConfig.java
  src/main/java/com/skhuedin/skhuedin/controller/AdminController.java
  src/main/java/com/skhuedin/skhuedin/controller/BlogApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/ProfileController.java
  src/main/java/com/skhuedin/skhuedin/dto/posts/PostsAdminResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/user/UserSaveRequestDto.java
  src/main/java/com/skhuedin/skhuedin/repository/CategoryRepository.java
  src/main/java/com/skhuedin/skhuedin/service/BlogService.java
  src/main/resources/application-local-resources.yml
  src/main/resources/application-local.yml
  src/main/resources/application-real1.yml
  src/main/resources/application-real2.yml
  src/main/resources/application.yml
  src/test/java/com/skhuedin/skhuedin/dto/user/UserUpdateDtoTest.java
Labels: 개발

#122 [FEAT] main page를 채우기 위한 main api 추가
  src/main/java/com/skhuedin/skhuedin/controller/api/BlogApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/CommentApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/FollowApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/MainApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/PostsApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/QuestionApiController.java
  src/main/java/com/skhuedin/skhuedin/controller/api/UserApiController.java
  src/main/java/com/skhuedin/skhuedin/domain/Posts.java
  src/main/java/com/skhuedin/skhuedin/dto/category/CategoryMainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/dto/main/MainResponseDto.java
  src/main/java/com/skhuedin/skhuedin/repository/CategoryRepository.java
  src/main/java/com/skhuedin/skhuedin/repository/PostsRepository.java
  src/main/java/com/skhuedin/skhuedin/service/CategoryService.java
  src/main/java/com/skhuedin/skhuedin/service/PostsService.java
  src/test/java/com/skhuedin/skhuedin/repository/PostsRepositoryTest.java
  src/test/java/com/skhuedin/skhuedin/service/CategoryServiceTest.java
  src/test/java/com/skhuedin/skhuedin/service/PostsServiceTest.java
Labels: 개발
